name: Build Mustache

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile Mustache dylib
        run: |
          xcrun -sdk iphoneos clang -dynamiclib -arch arm64 -framework UIKit -framework Foundation -o Mustache.dylib Mustache.m
          
      - name: Upload Mustache Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mustache-Dylib
          path: Mustache.dylib
